<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Eto.WinUI</RootNamespace>
    <!--<UseWinUI>true</UseWinUI>-->
    <!--<EnableMsixTooling>false</EnableMsixTooling>
    <WindowsPackageType>None</WindowsPackageType>-->
    <PackageId>Eto.Platform.WinUI</PackageId>
    <DefineConstants>$(DefineConstants);WINUI</DefineConstants>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'netstandard1.0'">
    <!-- This property tells Uno’s source generation tasks to skip work on netstandard1.0 -->
    <!--<UnoSourceGenerationSkip>true</UnoSourceGenerationSkip>-->
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Update="WinRT.Runtime" ExcludeAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <!-- This tells MSBuild to update the WinRT SDK reference so it contributes no assets -->
    <PackageReference Update="Microsoft.Windows.SDK.Net.Ref" PrivateAssets="all" ExcludeAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.UI.Xaml" Alias="mux" />
    <Using Include="Microsoft.UI.Xaml.Media" Alias="muxm" />
    <Using Include="Microsoft.UI.Dispatching" Alias="mud" />
    <Using Include="Microsoft.UI.Xaml.Controls" Alias="muc" />
    <Using Include="Windows.Foundation" Alias="sw" />
    <Using Include="Windows.Foundation" Alias="wf" />
    <Using Include="Windows.UI" Alias="wu" />
    <Using Include="Microsoft.UI" Alias="mu" />
  </ItemGroup>


  <ItemGroup>
    <!-- Replace the missing DataGrid package reference: -->
    <PackageReference Include="Uno.WinUI.Skia.Gtk" Version="5.6.0" />
    <!--<PackageReference Include="Uno.WinRT" Version="5.7.0"/>-->
    <!--<PackageReference Include="Uno.Toolkit.WinUI" Version="7.0.2" />-->
    <PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls.DataGrid" Version="7.0.2" />
    <PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls" Version="7.0.2" />
    <PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls.Core" Version="7.0.2" />
    <PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls.Layout" Version="7.0.2" />

    <!-- Replace the Controls.Primitives reference with the correct Uno package: -->
    <PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls.Primitives" Version="7.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Eto\Eto.csproj" />
  </ItemGroup>


</Project>
