<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Eto.Test.WinUI</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>AnyCPU;x64;arm64</Platforms>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>false</EnableMsixTooling>
    <WindowsPackageType>None</WindowsPackageType>
    <UnoSourceGeneratorUnsecureBinLogEnabled>true</UnoSourceGeneratorUnsecureBinLogEnabled>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\StoreLogo.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.3916" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <!-- 
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Eto.WinUI\Eto.WinUI.csproj" />
    <ProjectReference Include="..\Eto.Test\Eto.Test.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <UnoUIUseRoslynSourceGenerators>true</UnoUIUseRoslynSourceGenerators>
  </PropertyGroup>

  <ItemGroup>
    <!-- Replace the missing DataGrid package reference: -->
    <PackageReference Include="Uno.WinUI.Skia.Gtk" Version="5.6.0" />
    <!--<PackageReference Include="Uno.WinRT" Version="5.6.0" />-->
    <PackageReference Include="Uno.Toolkit.WinUI" Version="5.6.0" />
    <PackageReference Include="Uno.WinUI" Version="5.6.0" />
    <!--<PackageReference Include="Uno.WinRT" Version="5.7.0"/>-->
    <!--<PackageReference Include="Uno.Toolkit.WinUI" Version="7.0.2" />-->
    <PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls.DataGrid" Version="7.0.2" />
    <PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls" Version="7.0.2" />
    <PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls.Core" Version="7.0.2" />
    <PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls.Layout" Version="7.0.2" />

    <!-- Replace the Controls.Primitives reference with the correct Uno package: -->
    <PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls.Primitives" Version="7.0.2" />
  </ItemGroup>

  <!-- 
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution 
    Explorer "Package and Publish" context menu entry to be enabled for this project even if 
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>
</Project>
