<Project Sdk="Uno.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\..\..\src\Eto.WinUI\Eto.WinUI.U\Eto.WinUI.U.csproj">
            <!--<Aliases>EtoRef</Aliases>-->
        </ProjectReference>
        <ProjectReference Include="..\..\Eto.Test\Eto.Test.csproj" />

    </ItemGroup>
    <ItemGroup />
    <ItemGroup>
      <!--<PackageReference Include="Uno.WinUI.Runtime.WebAssembly" />-->
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="SkiaSharp" />
      <PackageReference Include="SkiaSharp.Views" />
    </ItemGroup>
    <PropertyGroup>
        <AssemblyName>Eto.Test.WinUI</AssemblyName>
        <RootNamespace>Eto.Test.WinUI</RootNamespace>
    </PropertyGroup>
  <PropertyGroup>
    <TargetFrameworks>net9.0-android;net9.0-ios;net9.0-browserwasm;net9.0-desktop</TargetFrameworks>

    <OutputType>Exe</OutputType>
    <UnoSingleProject>true</UnoSingleProject>

    <!-- Display name -->
    <ApplicationTitle>Eto.Test.UWinUI</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>com.companyname.eto-test-uwinui</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <!-- Package Publisher -->
    <ApplicationPublisher>Eto.Test.UWinUI</ApplicationPublisher>
    <!-- Package Description -->
    <Description>Eto.Test.UWinUI powered by Uno Platform.</Description>
      


      <!--
      UnoFeatures let's you quickly add and manage implicit package references based on the features you want to use.
      https://aka.platform.uno/singleproject-features
    -->
      <WasmBuildNative>true</WasmBuildNative>
    <UnoFeatures>
        <!--SkiaRenderer;-->
    </UnoFeatures>
  </PropertyGroup>
    <PropertyGroup>
        <UnoUISourceGeneratorDebuggerBreak>True</UnoUISourceGeneratorDebuggerBreak>
    </PropertyGroup>
    <!--<ItemGroup>
        <PackageReference Remove="Uno.WinUI.Runtime.WebAssembly" />
        <PackageReference Remove="Uno.WinUI.WebAssembly" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Remove="Uno.SkiaSharp.Views" />
    </ItemGroup>-->
    


</Project>
